# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2026-07"

[[extensions]]
name = "subscription-portal"
handle = "subscription-portal"
type = "ui_extension"
uid = "eff27c16-b5da-5b4a-762c-c49dde455125b9cbaafe"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/index.jsx"
target = "customer-account.page.render"

[extensions.capabilities]
api_access = true
network_access = true
